### ISSUE TITLE
When you used InstructPix2Pix, how is the resolution of the image set? 

### ISSUE THREAD

**Issue by HDUyiming** [aiiu-lab/BlenDA#1]
This is a fascinating work! However, I have some questions about the translated image.
When you used InstructPix2Pix, how is the resolution of the image set? 
For example, the resolution of BDD100K is 1280*720, what resolution do you shrink to when generating the translated image?
What command did you use to generate images of an entire dataset 
I hope to get your help, thank you very much!

**Comment by Jason-user** [comment]
Hello, thank you for your comment.
To generate translated images using InstructPix2Pix, resize the length to 512 while ensuring that the width is divisible by the same factor. Additionally, ensure that the width after resizing can be divided by 64 to accommodate the downsample in the Diffusion model. After generating the translated image, revert it back to its original resolution. As an illustration, BDD100K images typically have a resolution of 1280x720. These images should be resized to 512x320 for processing with the Diffusion model and then restored back to their original resolution of 1280x720. 

Here is the code we use to resize the image:
width_o, height_o = input_image.size   ###(width_o, height_o represent original resolution)
factor = 512 / max(width_o, height_o)
factor = math.ceil(min(width_o, height_o) * factor / 64) * 64 / min(width_o, height_o)
width = int((width_o * factor) // 64) * 64
height = int((height_o * factor) // 64) * 64
input_image = ImageOps.fit(input_image, (width, height), method=Image.Resampling.LANCZOS)  ###(input_image is the image sent to the Diffusion model)

**Comment by HDUyiming** [comment]
Thank you for your kind reply！
I just used instruct p2p to generate images of BDD100K from day to night these days 
My specific details are:
    parser.add_argument("--resolution", default=640, type=int)
    parser.add_argument("--steps", default=25, type=int)
    seed id random
After generating the translated image, revert it to its original resolution （this is the same with you）
edited_image = ImageOps.fit(edited_image, (width, height), method=Image.Resampling.LANCZOS)
The image generation rate is 5 seconds per image.
The prompt is "turn it into night time" (We found that this prompt can effectively prevent objects from being obscured )
---------------------------------------------------------------------------------------------
May I ask you if there is anything wrong with my procedure ?
Does random seed selection random or fixed have a high quality for image generation?

**Comment by Jason-user** [comment]
1. In our experiment, we set the number of steps to 50 for generating the translated images. You just have to make sure the length of the image before inputting into the Diffusion model should be resized to 512, and the width should be divisible by the same factor, ensuring it can also be divided by 64.
2. We initially test various seeds to assess the quality of the output images. Following this, we generate the translated images using the fixed seed, specifically the one with the best quality.
